[workspace]
members = [
    "cargo-n64",
    "examples/n64lib",
    "examples/hello-ipl3font",
]

[profile.release]
lto = "thin"

[patch.crates-io]
rrt0 = { path = "../rrt0", features = ["doctest"] }
