[workspace]
members = [
    "cargo-n64",
    "examples/n64lib",
    "examples/hello-ipl3font",
]

[profile.release]
lto = "thin"

[patch.crates-io]
rrt0 = { git = "https://github.com/rust-console/rrt0.git", rev = "4d1cafd509db06798a049af983300cf52cf55bbf" }
